"""RITUAL habit engine.

Pure-logic core for SPEC-habit-engine-v1. No I/O, no framework, no ORM — the
rules that PLAN-phase1-v1 §7 gates on are all testable without infrastructure.
"""

from .models import (
    Anchor,
    AnchorClass,
    CompletionSource,
    FadeLevel,
    Habit,
    HabitState,
    Occurrence,
    Outcome,
    PromptPolicy,
    Stability,
    StabilityBasis,
    StabilityReport,
)
from .scheduling import (
    generate_occurrences,
    is_quiet_hours,
    miss_detection_due_at,
    resolve_local,
    window_for,
)
from .stability import (
    circular_mad_minutes,
    circular_mean_time,
    score_anchor,
)
from .fading import (
    advance,
    assign_prompt_policies,
    is_unprompted,
    regress,
    resolve_outcome,
    should_advance,
    unprompted_rate,
)
from .chains import (
    MAX_CHAIN_LENGTH,
    Chain,
    ChainError,
    add_habit,
    can_add,
    cue_for,
    prompt_target,
    remove_habit,
    should_prompt,
)
from .graduation import (
    COMPLETION_FLOOR,
    REQUIRED_CONSECUTIVE_MEASURES,
    SRBAI_THRESHOLD,
    GraduationCheck,
    SRBAIMeasure,
    check_graduation,
    consecutive_passing_measures,
    graduation_message,
    maintenance_check_dates,
    next_measure_due,
    trailing_completion_rate,
)

__all__ = [
    "Anchor",
    "AnchorClass",
    "CompletionSource",
    "FadeLevel",
    "Habit",
    "HabitState",
    "Occurrence",
    "Outcome",
    "PromptPolicy",
    "Stability",
    "StabilityBasis",
    "StabilityReport",
    "generate_occurrences",
    "is_quiet_hours",
    "miss_detection_due_at",
    "resolve_local",
    "window_for",
    "circular_mad_minutes",
    "circular_mean_time",
    "score_anchor",
    "advance",
    "assign_prompt_policies",
    "is_unprompted",
    "regress",
    "resolve_outcome",
    "should_advance",
    "unprompted_rate",
    "COMPLETION_FLOOR",
    "REQUIRED_CONSECUTIVE_MEASURES",
    "SRBAI_THRESHOLD",
    "GraduationCheck",
    "SRBAIMeasure",
    "check_graduation",
    "consecutive_passing_measures",
    "graduation_message",
    "maintenance_check_dates",
    "next_measure_due",
    "trailing_completion_rate",
    "MAX_CHAIN_LENGTH",
    "Chain",
    "ChainError",
    "add_habit",
    "can_add",
    "cue_for",
    "prompt_target",
    "remove_habit",
    "should_prompt",
]
